"""Tambah kolom created_at di konsumsi_aktual

Revision ID: 08355b0aa6b2
Revises: 8306fe0b170b
Create Date: 2025-08-28 12:30:23.968105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08355b0aa6b2'
down_revision = '8306fe0b170b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenis_bangunan', schema=None) as batch_op:
        batch_op.alter_column('jenis',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('kategori_golongan', schema=None) as batch_op:
        batch_op.alter_column('golongan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('kode', schema=None) as batch_op:
        batch_op.alter_column('kode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('rute', schema=None) as batch_op:
        batch_op.alter_column('rute',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rute', schema=None) as batch_op:
        batch_op.alter_column('rute',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('kode', schema=None) as batch_op:
        batch_op.alter_column('kode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('kategori_golongan', schema=None) as batch_op:
        batch_op.alter_column('golongan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('jenis_bangunan', schema=None) as batch_op:
        batch_op.alter_column('jenis',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
