"""Tambah kolom upload_file di konsumsi_aktual

Revision ID: 5d9e90b4fab9
Revises: 08355b0aa6b2
Create Date: 2025-08-28 14:49:39.926784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9e90b4fab9'
down_revision = '08355b0aa6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.drop_column('upload_file')

    # ### end Alembic commands ###
