"""Add profile fields

Revision ID: a700b24e1b33
Revises: 5d9e90b4fab9
Create Date: 2025-08-28 18:37:53.256466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a700b24e1b33'
down_revision = '5d9e90b4fab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('family_contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('social_media')
        batch_op.drop_column('family_contact')
        batch_op.drop_column('education')
        batch_op.drop_column('position')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
