"""add is_simulasi to konsumsi_aktual

Revision ID: d12e54f8155c
Revises: 3dc6bf8e1e9a
Create Date: 2026-01-26 12:53:05.541280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12e54f8155c'
down_revision = '3dc6bf8e1e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_simulasi', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konsumsi_aktual', schema=None) as batch_op:
        batch_op.drop_column('is_simulasi')

    # ### end Alembic commands ###
