"""recreate forecast table

Revision ID: d42a05697879
Revises: fabf928574cd
Create Date: 2025-08-23 00:34:36.690239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42a05697879'
down_revision = 'fabf928574cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rute_id', sa.Integer(), nullable=False),
    sa.Column('kode_id', sa.Integer(), nullable=True),
    sa.Column('kategori_golongan_id', sa.Integer(), nullable=True),
    sa.Column('jenis_bangunan_id', sa.Integer(), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('periode', sa.Date(), nullable=False),
    sa.Column('prediksi', sa.Float(), nullable=False),
    sa.Column('aktual', sa.Float(), nullable=True),
    sa.Column('tanggal_entry', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['jenis_bangunan_id'], ['jenis_bangunan.id'], ),
    sa.ForeignKeyConstraint(['kategori_golongan_id'], ['kategori_golongan.id'], ),
    sa.ForeignKeyConstraint(['kode_id'], ['kode.id'], ),
    sa.ForeignKeyConstraint(['rute_id'], ['rute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jenis_bangunan', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_jenis_bangunan_jenis', ['jenis'])

    with op.batch_alter_table('kategori_golongan', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kategori_golongan_kategori', ['kategori'])

    with op.batch_alter_table('kode', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kode_kode', ['kode'])

    with op.batch_alter_table('rute', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rute_rute', ['rute'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rute', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('kode', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('kategori_golongan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('jenis_bangunan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('forecast')
    # ### end Alembic commands ###
