"""create table konsumsi_aktual

Revision ID: fabf928574cd
Revises: 8fe85472aa89
Create Date: 2025-08-03 00:35:10.302780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabf928574cd'
down_revision = '8fe85472aa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konsumsi_aktual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('bulan', sa.String(length=20), nullable=True),
    sa.Column('rute', sa.String(length=50), nullable=True),
    sa.Column('kode', sa.String(length=10), nullable=True),
    sa.Column('jenis_bangunan', sa.String(length=100), nullable=True),
    sa.Column('jumlah_sr', sa.Integer(), nullable=True),
    sa.Column('kategori_golongan', sa.String(length=20), nullable=True),
    sa.Column('konsumsi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('konsumsi_aktual')
    # ### end Alembic commands ###
